// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Simbice.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <Simbice.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <Ice/Object.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __Simbice__ClientCallback__acceptNewState_name = "acceptNewState";

const ::std::string __Simbice__SimbiconServer__addClient_name = "addClient";

const ::std::string __Simbice__SimbiconServer__acceptClientState_name = "acceptClientState";

}

namespace Ice
{
}
::IceProxy::Ice::Object* ::IceProxy::Simbice::upCast(::IceProxy::Simbice::ClientCallback* p) { return p; }

void
::IceProxy::Simbice::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::Simbice::ClientCallback>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::Simbice::ClientCallback;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::Simbice::ClientCallback::acceptNewState(const ::Simbice::AllState& newState, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __Simbice__ClientCallback__acceptNewState_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::Simbice::ClientCallback* __del = dynamic_cast< ::IceDelegate::Simbice::ClientCallback*>(__delBase.get());
            __del->acceptNewState(newState, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::Simbice::ClientCallback::begin_acceptNewState(const ::Simbice::AllState& newState, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __Simbice__ClientCallback__acceptNewState_name, __del, __cookie);
    try
    {
        __result->__prepare(__Simbice__ClientCallback__acceptNewState_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(newState);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::Simbice::ClientCallback::end_acceptNewState(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __Simbice__ClientCallback__acceptNewState_name);
}

const ::std::string&
IceProxy::Simbice::ClientCallback::ice_staticId()
{
    return ::Simbice::ClientCallback::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::Simbice::ClientCallback::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::Simbice::ClientCallback);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::Simbice::ClientCallback::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::Simbice::ClientCallback);
}

::IceProxy::Ice::Object*
IceProxy::Simbice::ClientCallback::__newInstance() const
{
    return new ClientCallback;
}
::IceProxy::Ice::Object* ::IceProxy::Simbice::upCast(::IceProxy::Simbice::SimbiconServer* p) { return p; }

void
::IceProxy::Simbice::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::Simbice::SimbiconServer>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::Simbice::SimbiconServer;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::Simbice::SimbiconServer::addClient(const ::Ice::Identity& ident, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __Simbice__SimbiconServer__addClient_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::Simbice::SimbiconServer* __del = dynamic_cast< ::IceDelegate::Simbice::SimbiconServer*>(__delBase.get());
            __del->addClient(ident, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::Simbice::SimbiconServer::begin_addClient(const ::Ice::Identity& ident, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __Simbice__SimbiconServer__addClient_name, __del, __cookie);
    try
    {
        __result->__prepare(__Simbice__SimbiconServer__addClient_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(ident);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::Simbice::SimbiconServer::end_addClient(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __Simbice__SimbiconServer__addClient_name);
}

void
IceProxy::Simbice::SimbiconServer::acceptClientState(const ::Simbice::AllState& oldState, const ::Ice::Identity& ident, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __Simbice__SimbiconServer__acceptClientState_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::Simbice::SimbiconServer* __del = dynamic_cast< ::IceDelegate::Simbice::SimbiconServer*>(__delBase.get());
            __del->acceptClientState(oldState, ident, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::Simbice::SimbiconServer::begin_acceptClientState(const ::Simbice::AllState& oldState, const ::Ice::Identity& ident, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __Simbice__SimbiconServer__acceptClientState_name, __del, __cookie);
    try
    {
        __result->__prepare(__Simbice__SimbiconServer__acceptClientState_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(oldState);
        __os->write(ident);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::Simbice::SimbiconServer::end_acceptClientState(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __Simbice__SimbiconServer__acceptClientState_name);
}

const ::std::string&
IceProxy::Simbice::SimbiconServer::ice_staticId()
{
    return ::Simbice::SimbiconServer::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::Simbice::SimbiconServer::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::Simbice::SimbiconServer);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::Simbice::SimbiconServer::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::Simbice::SimbiconServer);
}

::IceProxy::Ice::Object*
IceProxy::Simbice::SimbiconServer::__newInstance() const
{
    return new SimbiconServer;
}

void
IceDelegateM::Simbice::ClientCallback::acceptNewState(const ::Simbice::AllState& newState, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __Simbice__ClientCallback__acceptNewState_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(newState);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(__og.hasResponse())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.readEmptyParams();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

void
IceDelegateM::Simbice::SimbiconServer::addClient(const ::Ice::Identity& ident, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __Simbice__SimbiconServer__addClient_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(ident);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(__og.hasResponse())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.readEmptyParams();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

void
IceDelegateM::Simbice::SimbiconServer::acceptClientState(const ::Simbice::AllState& oldState, const ::Ice::Identity& ident, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __Simbice__SimbiconServer__acceptClientState_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(oldState);
        __os->write(ident);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(__og.hasResponse())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.readEmptyParams();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

void
IceDelegateD::Simbice::ClientCallback::acceptNewState(const ::Simbice::AllState& newState, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::Simbice::AllState& __p_newState, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_newState(__p_newState)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::Simbice::ClientCallback* servant = dynamic_cast< ::Simbice::ClientCallback*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->acceptNewState(_m_newState, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        const ::Simbice::AllState& _m_newState;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __Simbice__ClientCallback__acceptNewState_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(newState, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

void
IceDelegateD::Simbice::SimbiconServer::addClient(const ::Ice::Identity& ident, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::Ice::Identity& __p_ident, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_ident(__p_ident)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::Simbice::SimbiconServer* servant = dynamic_cast< ::Simbice::SimbiconServer*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->addClient(_m_ident, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        const ::Ice::Identity& _m_ident;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __Simbice__SimbiconServer__addClient_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(ident, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

void
IceDelegateD::Simbice::SimbiconServer::acceptClientState(const ::Simbice::AllState& oldState, const ::Ice::Identity& ident, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::Simbice::AllState& __p_oldState, const ::Ice::Identity& __p_ident, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_oldState(__p_oldState),
            _m_ident(__p_ident)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::Simbice::SimbiconServer* servant = dynamic_cast< ::Simbice::SimbiconServer*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->acceptClientState(_m_oldState, _m_ident, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        const ::Simbice::AllState& _m_oldState;
        const ::Ice::Identity& _m_ident;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __Simbice__SimbiconServer__acceptClientState_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(oldState, ident, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

::Ice::Object* Simbice::upCast(::Simbice::ClientCallback* p) { return p; }

namespace
{
const ::std::string __Simbice__ClientCallback_ids[2] =
{
    "::Ice::Object",
    "::Simbice::ClientCallback"
};

}

bool
Simbice::ClientCallback::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__Simbice__ClientCallback_ids, __Simbice__ClientCallback_ids + 2, _s);
}

::std::vector< ::std::string>
Simbice::ClientCallback::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__Simbice__ClientCallback_ids[0], &__Simbice__ClientCallback_ids[2]);
}

const ::std::string&
Simbice::ClientCallback::ice_id(const ::Ice::Current&) const
{
    return __Simbice__ClientCallback_ids[1];
}

const ::std::string&
Simbice::ClientCallback::ice_staticId()
{
    return __Simbice__ClientCallback_ids[1];
}

::Ice::DispatchStatus
Simbice::ClientCallback::___acceptNewState(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::Simbice::AllState newState;
    __is->read(newState);
    __inS.endReadParams();
    acceptNewState(newState, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __Simbice__ClientCallback_all[] =
{
    "acceptNewState",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

::Ice::DispatchStatus
Simbice::ClientCallback::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__Simbice__ClientCallback_all, __Simbice__ClientCallback_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __Simbice__ClientCallback_all)
    {
        case 0:
        {
            return ___acceptNewState(in, current);
        }
        case 1:
        {
            return ___ice_id(in, current);
        }
        case 2:
        {
            return ___ice_ids(in, current);
        }
        case 3:
        {
            return ___ice_isA(in, current);
        }
        case 4:
        {
            return ___ice_ping(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
Simbice::ClientCallback::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
Simbice::ClientCallback::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
Simbice::__patch(ClientCallbackPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::Simbice::ClientCallbackPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::Simbice::ClientCallback::ice_staticId(), v);
    }
}

::Ice::Object* Simbice::upCast(::Simbice::SimbiconServer* p) { return p; }

namespace
{
const ::std::string __Simbice__SimbiconServer_ids[2] =
{
    "::Ice::Object",
    "::Simbice::SimbiconServer"
};

}

bool
Simbice::SimbiconServer::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__Simbice__SimbiconServer_ids, __Simbice__SimbiconServer_ids + 2, _s);
}

::std::vector< ::std::string>
Simbice::SimbiconServer::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__Simbice__SimbiconServer_ids[0], &__Simbice__SimbiconServer_ids[2]);
}

const ::std::string&
Simbice::SimbiconServer::ice_id(const ::Ice::Current&) const
{
    return __Simbice__SimbiconServer_ids[1];
}

const ::std::string&
Simbice::SimbiconServer::ice_staticId()
{
    return __Simbice__SimbiconServer_ids[1];
}

::Ice::DispatchStatus
Simbice::SimbiconServer::___addClient(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::Ice::Identity ident;
    __is->read(ident);
    __inS.endReadParams();
    addClient(ident, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
Simbice::SimbiconServer::___acceptClientState(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::Simbice::AllState oldState;
    ::Ice::Identity ident;
    __is->read(oldState);
    __is->read(ident);
    __inS.endReadParams();
    acceptClientState(oldState, ident, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __Simbice__SimbiconServer_all[] =
{
    "acceptClientState",
    "addClient",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

::Ice::DispatchStatus
Simbice::SimbiconServer::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__Simbice__SimbiconServer_all, __Simbice__SimbiconServer_all + 6, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __Simbice__SimbiconServer_all)
    {
        case 0:
        {
            return ___acceptClientState(in, current);
        }
        case 1:
        {
            return ___addClient(in, current);
        }
        case 2:
        {
            return ___ice_id(in, current);
        }
        case 3:
        {
            return ___ice_ids(in, current);
        }
        case 4:
        {
            return ___ice_isA(in, current);
        }
        case 5:
        {
            return ___ice_ping(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
Simbice::SimbiconServer::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
Simbice::SimbiconServer::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
Simbice::__patch(SimbiconServerPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::Simbice::SimbiconServerPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::Simbice::SimbiconServer::ice_staticId(), v);
    }
}
